# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: '3'
services:
  hub:
    image: selenium/hub
    ports:
      - '4555:4444'
    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 300
      GRID_TIMEOUT: 300
  

  chrome1:
    image: selenium/node-chrome-debug
    depends_on:
      - hub
    ports:
        - 9001:5900
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 2
      NODE_MAX_INSTANCES: 2
    volumes:
      - /dev/shm:/dev/shm
    links:
      - hub

  chrome2:
    image: selenium/node-firefox-debug
    depends_on:
      - hub
    ports:
        - 9002:5900
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 2
      NODE_MAX_INSTANCES: 2
    volumes:
        - /dev/shm:/dev/shm
    links:
      - hub
      
  chrome3:
    image: selenium/node-opera-debug
    depends_on:
      - hub
    ports:
        - 9003:5900
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 2
      NODE_MAX_INSTANCES: 2
    volumes:
        - /dev/shm:/dev/shm
    links:
      - hub